### ISSUE TITLE
ModuleNotFoundError: No module named 'visa_mock'

### ISSUE THREAD

**Issue by Ednaldo-Cruz** [arturaugusto/LME-Python#1]
Descrição do errro

Traceback (most recent call last):
  File "D:\Users\ednaldoc\WPy\teste.py", line 52, in <module>
    from visa_mock import visa
ModuleNotFoundError: No module named 'visa_mock'

**Comment by arturaugusto** [comment]
Você copiou o arquivo [visa_mock.py](https://github.com/arturaugusto/LME-Python/blob/master/visa_mock.py) na mesma pasta que está o teste.py?

**Comment by Ednaldo-Cruz** [comment]
sim.

**Comment by arturaugusto** [comment]
Manda o código do seu arquivo D:\Users\ednaldoc\WPy\teste.py

**Comment by Ednaldo-Cruz** [comment]
from visa_mock import visa
rm = visa.ResourceManager()

dmm = rm.open_resource('GPIB0::22::INSTR', timeout = 50000)
dmm.query('*CLS;*OPC?')

cal = rm.open_resource('GPIB0::7::INSTR', timeout = 10000)
cal.query('*SRE 32;*ESE 1;*CLS;*OPC?')

print("ok")
dmm.query('CONF:VOLT:DC 10,MAX;*OPC?')
cal.query('OUT 5V, 0HZ;OPER;*OPC?')

leitura = dmm.query('READ?')

cal.query('STBY;*OPC?;')

print(leitura)

**Comment by arturaugusto** [comment]
Aqui consegui rodar normalmente.

Faz o seguite:

Baixa este arquivo, que contem todo o curso + o seu código:
https://github.com/arturaugusto/LME-Python/archive/master.zip

descompacta e executa o arquivo `teste_do_ed.py`

python teste_do_ed.py

E veja se funcionou.

**Comment by Ednaldo-Cruz** [comment]
criando um arquivo .bat pra executar o script, funciona mas pelo pyzo não...

**Comment by arturaugusto** [comment]
Tenta colocar o seguinte código no começo do seu arquivo:

```python
import os
path="D:\\Users\\ednaldoc\\WPy\\"
os.chdir(path)
```

Isto vai fazer com que ao executar `from visa_mock import visa`, o python buque por arquivos na pasta correta.
